#!/bin/sh
#
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push
# @author : Mak Sophea
# @version : 1.0
#

# check forbidden branch
FORBIDDEN_REF="refs/heads/master" # insert branch ref

remote="$1"
url="$2"

if read local_ref local_sha remote_ref remote_sha
then
    if [ "$remote_ref" == "$FORBIDDEN_REF" ]
    then
        echo "DO NOT PUSH it master"
        exit 1 # 금지된 ref 로 push 를 실행하면 에러
    fi
fi
# end check forbidden branch

##build the project
echo "============= build phase with test package =============="
./gradlew clean test
if [[ $? != 0 ]]; then
 echo "[[ fail :: build test is not successful ]]"
 exit 1
fi
